eureka.client.service-url.defaultZone=http://localhost:8761/eureka

jwt.secret=nimuairySecretKey
logging.level.org.springframework.web=DEBUG

server.port=9090
spring.application.name=gateway
spring.cloud.discovery.enabled=true
